#!/bin/python3

import math
import os
import random
import re
import sys



def check(num):
    if((num<1)or(num>100)):
        print("value out of range")

def main(num):
    check(num)

    if(num%2!= 0):
        print("Weird")
    elif(num%2 == 0):
        if((num>=2) and (num<=5)):
            print("Not Weird")
        elif((num>=6) and (num<=20)):
            print("Weird")
        else:
            print("Not Weird")
    


n = int(input())
main(n)

